# Generated by Django 5.2.5 on 2025-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ImageField(choices=[(1, 'Technology'), (2, 'Lifestyle'), (3, 'Sports'), (4, 'News'), (5, 'Other')], null=True, upload_to='', verbose_name='Category'),
        ),
    ]
