# Generated by Django 5.2.5 on 2025-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.IntegerField(choices=[(1, 'Technology'), (2, 'Lifestyle'), (3, 'Sports'), (4, 'News'), (5, 'Other')], null=True, verbose_name='Category'),
        ),
    ]
